# Generated by Django 4.0.4 on 2022-05-04 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appli_bball', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='joueur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomj', models.CharField(max_length=30)),
                ('prenom', models.CharField(max_length=30)),
                ('taille', models.DateField(max_length=30)),
                ('poids', models.CharField(max_length=30)),
                ('poste', models.CharField(max_length=30)),
                ('numero', models.CharField(max_length=30)),
                ('nbrtropheej', models.IntegerField(blank=True)),
            ],
        ),
    ]
