# Generated by Django 4.0.4 on 2022-05-15 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appli_bball', '0002_joueur_equipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joueur',
            name='poste',
            field=models.CharField(choices=[('/', 'Aucun'), ('PG', 'point guard'), ('SG', 'shooting guard'), ('SF', 'small forward'), ('PF', 'power forward'), ('C', 'center')], default='Aucun', max_length=10),
        ),
    ]
