# Generated by Django 4.0.4 on 2022-05-04 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appli_bball', '0002_joueur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joueur',
            name='taille',
            field=models.CharField(max_length=30),
        ),
    ]
